
services:
  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: syndicate-api
    ports:
      - '3000:3000'
    env_file:
     - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # command: npm run start:dev
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=syndicatedb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # # Redis Commander (Optional - Web UI for Redis)
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-commander
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   depends_on:
  #     - redis
  #   restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: