name: Deploy Syndicate

on:
  push:
    branches:
      - main
env:
  ECR_REPOSITORY: syndicate-repository
  ECS_CLUSTER: syndicate-cluster
  ECS_SERVICE: syndicate_service
  CONTAINER_NAME: syndicate

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
                  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        id: build
        env:
          IMAGE_TAG: ${{ github.sha }}
          run:  |
            echo "Building Docker image from Dockerfile..."
            docker build --target production -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
            echo "✅ Build complete: ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"
    
      - name: Tag image for ECR
        env:
          ECR_REGISTRY_URL: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Tagging image for ECR..."
          docker tag ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG \
            $ECR_REGISTRY_URL/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "✅ Tagged: $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"
      
    
        

      
      
    
